package com.minmai.wallet.common.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.minmai.wallet.moudles.db.DbUserInfo;
import com.minmai.wallet.common.greendao.DbCenterInfo;

import com.minmai.wallet.common.greendao.DbUserInfoDao;
import com.minmai.wallet.common.greendao.DbCenterInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dbUserInfoDaoConfig;
    private final DaoConfig dbCenterInfoDaoConfig;

    private final DbUserInfoDao dbUserInfoDao;
    private final DbCenterInfoDao dbCenterInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dbUserInfoDaoConfig = daoConfigMap.get(DbUserInfoDao.class).clone();
        dbUserInfoDaoConfig.initIdentityScope(type);

        dbCenterInfoDaoConfig = daoConfigMap.get(DbCenterInfoDao.class).clone();
        dbCenterInfoDaoConfig.initIdentityScope(type);

        dbUserInfoDao = new DbUserInfoDao(dbUserInfoDaoConfig, this);
        dbCenterInfoDao = new DbCenterInfoDao(dbCenterInfoDaoConfig, this);

        registerDao(DbUserInfo.class, dbUserInfoDao);
        registerDao(DbCenterInfo.class, dbCenterInfoDao);
    }
    
    public void clear() {
        dbUserInfoDaoConfig.clearIdentityScope();
        dbCenterInfoDaoConfig.clearIdentityScope();
    }

    public DbUserInfoDao getDbUserInfoDao() {
        return dbUserInfoDao;
    }

    public DbCenterInfoDao getDbCenterInfoDao() {
        return dbCenterInfoDao;
    }

}
