package com.minmai.wallet.common.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.minmai.wallet.moudles.db.DbBankInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_BANK_INFO".
*/
public class DbBankInfoDao extends AbstractDao<DbBankInfo, Long> {

    public static final String TABLENAME = "DB_BANK_INFO";

    /**
     * Properties of entity DbBankInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property BankId = new Property(1, String.class, "bankId", false, "BANK_ID");
        public final static Property BankName = new Property(2, String.class, "bankName", false, "BANK_NAME");
        public final static Property BankShortName = new Property(3, String.class, "bankShortName", false, "BANK_SHORT_NAME");
    }


    public DbBankInfoDao(DaoConfig config) {
        super(config);
    }
    
    public DbBankInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_BANK_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"BANK_ID\" TEXT," + // 1: bankId
                "\"BANK_NAME\" TEXT," + // 2: bankName
                "\"BANK_SHORT_NAME\" TEXT);"); // 3: bankShortName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_BANK_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbBankInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String bankId = entity.getBankId();
        if (bankId != null) {
            stmt.bindString(2, bankId);
        }
 
        String bankName = entity.getBankName();
        if (bankName != null) {
            stmt.bindString(3, bankName);
        }
 
        String bankShortName = entity.getBankShortName();
        if (bankShortName != null) {
            stmt.bindString(4, bankShortName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbBankInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String bankId = entity.getBankId();
        if (bankId != null) {
            stmt.bindString(2, bankId);
        }
 
        String bankName = entity.getBankName();
        if (bankName != null) {
            stmt.bindString(3, bankName);
        }
 
        String bankShortName = entity.getBankShortName();
        if (bankShortName != null) {
            stmt.bindString(4, bankShortName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbBankInfo readEntity(Cursor cursor, int offset) {
        DbBankInfo entity = new DbBankInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // bankId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // bankName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // bankShortName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbBankInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBankId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBankName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setBankShortName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbBankInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbBankInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DbBankInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
