package com.minmai.wallet.common.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DB_CENTER_INFO".
*/
public class DbCenterInfoDao extends AbstractDao<DbCenterInfo, Long> {

    public static final String TABLENAME = "DB_CENTER_INFO";

    /**
     * Properties of entity DbCenterInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, String.class, "userId", false, "USER_ID");
        public final static Property ExtendOne = new Property(2, String.class, "extendOne", false, "EXTEND_ONE");
        public final static Property UserNo = new Property(3, String.class, "userNo", false, "USER_NO");
    }


    public DbCenterInfoDao(DaoConfig config) {
        super(config);
    }
    
    public DbCenterInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DB_CENTER_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" TEXT," + // 1: userId
                "\"EXTEND_ONE\" TEXT," + // 2: extendOne
                "\"USER_NO\" TEXT);"); // 3: userNo
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DB_CENTER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DbCenterInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String extendOne = entity.getExtendOne();
        if (extendOne != null) {
            stmt.bindString(3, extendOne);
        }
 
        String userNo = entity.getUserNo();
        if (userNo != null) {
            stmt.bindString(4, userNo);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DbCenterInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
 
        String extendOne = entity.getExtendOne();
        if (extendOne != null) {
            stmt.bindString(3, extendOne);
        }
 
        String userNo = entity.getUserNo();
        if (userNo != null) {
            stmt.bindString(4, userNo);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DbCenterInfo readEntity(Cursor cursor, int offset) {
        DbCenterInfo entity = new DbCenterInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // extendOne
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // userNo
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DbCenterInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setExtendOne(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUserNo(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DbCenterInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DbCenterInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DbCenterInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
